package net.runelite.client.plugins.microbot.doom.data;

import net.runelite.api.coords.WorldPoint;

import java.util.Arrays;
import java.util.List;

/**
 * Meta tile markers for Doom of Mokhaiotl, parsed directly from the
 * RuneLite region-tile-marker export (region 14180, plane 0).
 *
 * Region 14180 = 0x3764, so the arena base is:
 *   baseX = (0x37 << 6) = 3520
 *   baseY = (0x64 << 6) = 6400
 * and every marker's world point is (3520 + regionX, 6400 + regionY, 0).
 *
 * Only the WEST-side meta set is encoded here, because that is the side the
 * guide actually plays. The arena is mirrored, so an east-side set can be
 * generated by reflecting X about the centre column (col 31/32) if you ever
 * want side selection.
 */
public final class DoomTiles
{
    public static final int BASE_X = 3520;
    public static final int BASE_Y = 6400;
    public static final int PLANE  = 0;

    private DoomTiles() {}

    /** Helper: build a WorldPoint from region-local coords. */
    public static WorldPoint local(int regionX, int regionY)
    {
        return new WorldPoint(BASE_X + regionX, BASE_Y + regionY, PLANE);
    }

    // ------------------------------------------------------------------
    // Start / B tiles
    // ------------------------------------------------------------------

    /** Waves 6-7 opener: run straight north to here, turn on range prayer. */
    public static final WorldPoint B_NORTH = local(31, 47);

    /** Waves 8+: open from the north-west B tile instead. */
    public static final WorldPoint B_NW = local(22, 47);

    /** B1: the rockblock / shadow-dodge tile you click one tick before the boulder explodes. */
    public static final WorldPoint B1 = local(28, 47);

    // ------------------------------------------------------------------
    // Transition lines (shield-phase -> car-phase safe rows).
    // Stand ON or BEHIND D1, then D2, then D3 as the eye pops each time.
    // ------------------------------------------------------------------

    /** D1 row (horizontal, y = 6443). First and foremost priority before car transition. */
    public static final List<WorldPoint> D1 = Arrays.asList(
        local(29, 43), local(30, 43), local(31, 43), local(32, 43), local(33, 43)
    );

    /** D2 column (vertical, x = 3546). Second transition row. */
    public static final List<WorldPoint> D2 = Arrays.asList(
        local(26, 45), local(26, 46), local(26, 47), local(26, 48), local(26, 49)
    );

    /** D3 row (horizontal, y = 6438). Third transition row / far safe line. */
    public static final List<WorldPoint> D3 = Arrays.asList(
        local(19, 38), local(20, 38), local(21, 38), local(22, 38), local(23, 38),
        local(24, 38), local(25, 38)
    );

    /** Representative single tiles (the labelled markers) for quick reference. */
    public static final WorldPoint D1_LABEL = local(31, 43);
    public static final WorldPoint D2_LABEL = local(26, 47);
    public static final WorldPoint D3_LABEL = local(22, 38);

    // ------------------------------------------------------------------
    // "White line" — the priority poison-clear lane during shockwave.
    // This is the lane you DPS the boss and kill grubs from, so clear it first.
    // ------------------------------------------------------------------

    public static final List<WorldPoint> WHITE_LINE = Arrays.asList(
        local(25, 40), local(25, 41), local(25, 42), local(26, 43), local(27, 43)
    );

    // ------------------------------------------------------------------
    // Rockblock pack (west) — from the wiki's Doom_Rockblock marker set.
    //   "1" gold  : stand here until the eye appears, first car slam
    //   "2" cyan  : move here for the second slam (rocks protect you)
    //   "3" purple: stand around here for the third slam
    //   "3t"      : stand beyond this row to drag the Doom one extra tick
    // ------------------------------------------------------------------

    public static final WorldPoint RB_1_GOLD   = local(28, 45);
    public static final WorldPoint RB_2_CYAN   = local(23, 44);
    public static final WorldPoint RB_3_PURPLE = local(24, 39);
    public static final WorldPoint RB_ROCK     = local(31, 47); // where the blocking rock should land

    public static final List<WorldPoint> RB_3T = Arrays.asList(
        local(25, 34), local(26, 34), local(28, 34)
    );

    // ------------------------------------------------------------------
    // Arena geometry helpers
    // ------------------------------------------------------------------

    /** Centre column of the arena; used for "grubs only from the western hemisphere" checks. */
    public static final int CENTRE_X = BASE_X + 31;

    /** True if a world point is on the west half (grubs / safe lanes live here). */
    public static boolean isWest(WorldPoint wp)
    {
        return wp.getX() <= CENTRE_X;
    }
}
